apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: internet-check-home
  labels:
    app: speedtest-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9798
      targetPort: 9798
      protocol: TCP
  selector:
    app: speedtest-exporter
